# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Jeremy Murphy
name: CI

concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
  
on:
  # Triggers on all pushes but skips tooling checks except on pushes to main (to run post-PR)
  push:
    paths-ignore:
      - "Dockerfile"
  #  branches: [ main ]
  # Triggers on ALL PRs regardless of location
  pull_request:
  # Allows manual workflow runs via the GitHub UI
  workflow_dispatch:
    inputs:
      notooling:
        description: "Skip clang-format and clang-tidy?"
        required: false
        type: boolean
        default: true

env:
  # Logic: (Standard triggers OR manual triggers) AND NOT explicitly skipped       
  USE_TOOLING: 

jobs:
  ci-build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/solusignis/ci-env-llvm:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          cmake --preset=clang-debug \
            -DBUILD_TESTING=ON \
            -DCMAKE_CXX_FLAGS="-nostdinc++ -isystem $GITHUB_WORKSPACE/libcxx-21/include/c++/v1 -nostdlib++ -Wall -Wextra -fcolor-diagnostics" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$GITHUB_WORKSPACE/libcxx-21/lib -lc++ -lc++abi -Wl,-rpath,$GITHUB_WORKSPACE/libcxx-21/lib"

      - name: Build
        run: cmake --build --preset=clang-debug

      - name: Run tests
        run: cmake --build --preset=clang-debug --target=tests.run

ci-tooling-clang_llvm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/solusignis/ci-env-llvm:latest

    if: >-
      ${{ 
        (
          github.event_name == 'pull_request' ||
          (github.event_name == 'push' && github.ref_name == 'main') ||
          github.event_name == 'workflow_dispatch'
        )
        && 
        (github.event.inputs.notooling != 'true')
      }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          cmake --preset=clang-debug \
            -DBUILD_TESTING=OFF \
            -DCMAKE_CXX_FLAGS="-nostdinc++ -isystem $GITHUB_WORKSPACE/libcxx-21/include/c++/v1 -nostdlib++ -Wall -Wextra -fcolor-diagnostics" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$GITHUB_WORKSPACE/libcxx-21/lib -lc++ -lc++abi -Wl,-rpath,$GITHUB_WORKSPACE/libcxx-21/lib"

      - name: clang-format check
        run: cmake --build --preset=clang-debug --target=format-check

      - name: Build
        run: cmake --build --preset=clang-debug
        
      - name: clang-tidy checks
        run: cmake --build --preset=clang-debug --target=tidy-check-fast
