# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Jeremy Murphy
name: CI

concurrency:
  group: >
    ci-${{ github.workflow }}-${
      { github.event_name == 'workflow_run'
        && github.event.workflow_run.head_branch
        || github.head_ref
        || github.ref_name
      }
    }
  cancel-in-progress: true
  
on:
  # Triggers on all pushes but skips tooling checks except on pushes to main (to run post-PR)
  push:
    paths-ignore:
      - "Dockerfile"
  #  branches: [ main ]
  # Triggers on ALL PRs regardless of location
  pull_request:
  # Allows manual workflow runs via the GitHub UI
  workflow_dispatch:
    inputs:
      tooling:
        description: "Run clang-format and clang-tidy?"
        required: false
        type: boolean
        default: false
  # Runs any time a new CI Docker image is built.
  # Runs after a VERSION file update by version-fix or branch_init.
  workflow_run:
    workflows:
      - "Publish CI Image"
      - "VERSION Fixer"
      - "Initialize Release Branch"
      - "Fix Formatting"
    types:
      - completed

jobs:
  clang-ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/solusignis/clang-ci-env:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          cmake --preset=clang-debug \
            -DCMAKE_CXX_FLAGS="-nostdinc++ -isystem $GITHUB_WORKSPACE/libcxx-21/include/c++/v1 -nostdlib++ -Wall -Wextra -fcolor-diagnostics" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$GITHUB_WORKSPACE/libcxx-21/lib -lc++ -lc++abi -Wl,-rpath,$GITHUB_WORKSPACE/libcxx-21/lib"

      - name: clang-format check
        if: github.event.inputs.tooling == 'true' || github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: cmake --build --preset=clang-debug --target=format-check

      - name: Build
        run: cmake --build --preset=clang-debug

      - name: Run tests
        run: cmake --build --preset=clang-debug --target=tests.run
        
      - name: clang-tidy checks
        if: github.event.inputs.tooling == 'true' || github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: cmake --build --preset=clang-debug --target=tidy-check-fast
